# Generated by Django 4.1.4 on 2023-01-21 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='スタジオ名')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='開始時間')),
                ('end', models.DateTimeField(verbose_name='終了時間')),
                ('personCount', models.IntegerField(verbose_name='人数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='予約完了日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='変更日時')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.studio', verbose_name='スタジオ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='予約者')),
            ],
        ),
    ]
